feat: Реализовать основной функционал приложения в main-service.
KirillBabichenko/java-explore-with-me pull request #4
Opened 2023-05-24 22:19 UTC by KirillBabichenko

- Реализовать основной функционал приложения в main-service. 
- Настроить взаимодействие main-service с сервисом статистики.

2023-05-25 17:54 UTC, AnastasiyaFomkina requested changes

2023-05-25 17:54 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/dto/CompilationDto.java
> +@Data
Все `@Data` нужно удалить из проекта. Нужно оставить только методы, которые действительно будут использоваться. Вот хорошая статья, вот отличная статья [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-05-25 17:54 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/dto/EventFullDto.java
> +    private String createdOn;
Поля с датой лучше получать в виде объекта, чтобы избежать ошибок парсинга из json можно явно задать паттерн с помощью [@JsonFormat](https://www.baeldung.com/spring-boot-formatting-json-dates)

2023-05-25 17:54 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/dto/EventFullDto.java
> +    private String title;
Тут не хватает валидации, например, для title можно добавить ограничение на длину поля

2023-05-25 17:54 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/dto/CompilationDto.java
Папку dto лучше тоже разбить на подпаки, как controller

2023-05-25 17:54 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/model/Category.java
> +@Data
Использование `@Data` в jpa-сущностях приводит к [вот этой проблеме](https://habr.com/ru/company/haulmont/blog/564682/)
 Все `@Data` в моделях нужно удалить

2023-05-25 17:54 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/repository/UserRepository.java
> +    @Query("select u from User as u")
А зачем тут `@Query`?

2023-05-25 17:54 UTC, AnastasiyaFomkina commented on main-service/src/main/resources/schema.sql
Предлагаю добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2023-05-25 21:40 UTC, KirillBabichenko commented on main-service/src/main/java/ru/practicum/dto/CompilationDto.java
> +@Data
Поправил.

2023-05-25 21:41 UTC, KirillBabichenko commented on main-service/src/main/java/ru/practicum/dto/EventFullDto.java
> +    private String createdOn;
Поправил.

2023-05-25 21:43 UTC, KirillBabichenko commented on main-service/src/main/java/ru/practicum/dto/CompilationDto.java
Валидацию добавил, но у меня вопрос действительно ли она тут нужна? EventFullDto используется только для выдачи результата из из данных полученных из БД, где все поля были ранее верифицированы при внесении.

2023-05-25 21:44 UTC, KirillBabichenko commented on main-service/src/main/java/ru/practicum/model/Category.java
> +@Data
Спасибо! Аннотации исправил.

2023-05-25 21:51 UTC, KirillBabichenko commented on main-service/src/main/java/ru/practicum/repository/UserRepository.java
> +    @Query("select u from User as u")
В одном из последних тестов "Поиск пользователей без параметра ids" постоянно выскакивала ошибка. Причем при прогонке тестов ошибка выпадала примерно в 30%. Не понимал причин и тестировал разные гипотезы. Одной из них было предположение, что стандартный метод поиска JpaReposytory по каким-то причинам не срабатывает. В итоге понял причину - в Postman при генерации ограниченное количество имен и они повторяются с какой-то перидичностью, а по ТЗ имя должно быть уникальным - в результате некоторые User не записывалась в базу и количество в тесте не совпадало с ожидаемым. 
Ну а метод с Query он же рабочий - ошибок не выдает. Убрать забыл. =)

2023-05-25 21:51 UTC, KirillBabichenko commented on main-service/src/main/resources/schema.sql
Добавил.

2023-05-26 14:04 UTC, AnastasiyaFomkina commented on main-service/src/main/java/ru/practicum/dto/CompilationDto.java
да, логично, не обратила внимание на то, что он только для ответа

2023-05-26 14:07 UTC, AnastasiyaFomkina approved these changes

2023-05-26 14:51 UTC, merged